import { Router } from 'express';

const router = Router();

// GET /api/pricing/config - Get pricing page configuration
router.get('/config', async (req, res) => {
  try {
    // In a real application, this would fetch from database
    // For now, returning the configuration that can be customized via admin UI
    const pricingData = {
      config: {
        brandName: process.env.BRAND_NAME || 'BrandMonkz',
        trustBadgeText: process.env.TRUST_BADGE_TEXT || 'Trusted by 10,000+ businesses worldwide',
        businessCount: process.env.BUSINESS_COUNT || '10,000+',
        salesEmail: process.env.SALES_EMAIL || process.env.SES_FROM_EMAIL || 'noreply@brandmonkz.com',
        trialDays: process.env.TRIAL_DAYS || '14',
        annualSavings: process.env.ANNUAL_SAVINGS || '17%',
        headline: process.env.PRICING_HEADLINE || 'Simple, transparent pricing for everyone',
        subheadline: process.env.PRICING_SUBHEADLINE || 'Choose the perfect plan for your business. Start with a free trial and scale as you grow.',
        ctaHeadline: process.env.CTA_HEADLINE || 'Ready to transform your business?',
        ctaSubheadline: process.env.CTA_SUBHEADLINE || 'Join {businessCount} businesses using {brandName} to grow faster and smarter',
        faqSectionTitle: process.env.FAQ_SECTION_TITLE || 'Frequently Asked Questions',
        faqSectionSubtitle: process.env.FAQ_SECTION_SUBTITLE || 'Everything you need to know about our pricing plans',
      },
      plans: [
        {
          id: 'free',
          name: process.env.PLAN_FREE_NAME || 'Free',
          icon: process.env.PLAN_FREE_ICON || 'Sparkles',
          description: process.env.PLAN_FREE_DESCRIPTION || 'Perfect for trying out BrandMonkz',
          monthlyPrice: 0,
          annualPrice: 0,
          popular: false,
          features: JSON.parse(process.env.PLAN_FREE_FEATURES || JSON.stringify([
            { text: '100 contacts', included: true },
            { text: '10 companies', included: true },
            { text: '20 deals', included: true },
            { text: '1 user only', included: true },
            { text: '50 emails/month', included: true },
            { text: '1 email template', included: true },
            { text: 'Basic email tracking (opens)', included: true },
            { text: 'Manual email campaigns', included: true },
            { text: 'Email automation', included: false },
            { text: 'AI features', included: false },
            { text: 'Video campaigns', included: false },
            { text: 'Team collaboration', included: false },
            { text: 'API access', included: false },
            { text: 'Priority support', included: false },
          ])),
          buttonText: process.env.PLAN_FREE_BUTTON_TEXT || 'Start Free',
          buttonVariant: 'outline' as 'primary' | 'outline',
          stripeMonthlyPriceId: '',
          stripeAnnualPriceId: '',
        },
        {
          id: 'starter',
          name: process.env.PLAN_1_NAME || 'Starter',
          icon: process.env.PLAN_1_ICON || 'Star',
          description: process.env.PLAN_1_DESCRIPTION || 'For solopreneurs & small businesses',
          monthlyPrice: Number.parseInt(process.env.PLAN_1_MONTHLY_PRICE || '49'),
          annualPrice: Number.parseInt(process.env.PLAN_1_ANNUAL_PRICE || '490'),
          popular: (process.env.PLAN_1_POPULAR || 'false') === 'true',
          features: JSON.parse(process.env.PLAN_1_FEATURES || JSON.stringify([
            { text: '2,500 contacts', included: true },
            { text: '250 companies', included: true },
            { text: '500 deals', included: true },
            { text: '3 team members', included: true },
            { text: '2,500 emails/month', included: true },
            { text: '10 email templates', included: true },
            { text: 'Email tracking (opens, clicks, replies)', included: true },
            { text: 'Gmail/SMTP/Google Workspace', included: true },
            { text: 'Basic email automation (3 workflows)', included: true },
            { text: 'Contact & company enrichment', included: true },
            { text: 'AI email composer (50 generations/mo)', included: true },
            { text: 'Activity tracking & timeline', included: true },
            { text: 'Tags & custom fields', included: true },
            { text: 'CSV import/export', included: true },
            { text: 'Video campaigns', included: false },
            { text: 'Lead discovery', included: false },
            { text: 'Team sharing & assignments', included: false },
            { text: 'Advanced analytics', included: false },
            { text: 'API access', included: false },
            { text: 'Priority support', included: false },
          ])),
          buttonText: process.env.PLAN_1_BUTTON_TEXT || 'Start Free Trial',
          buttonVariant: (process.env.PLAN_1_BUTTON_VARIANT || 'outline') as 'primary' | 'outline',
          stripeMonthlyPriceId: process.env.STRIPE_STARTER_MONTHLY!,
          stripeAnnualPriceId: process.env.STRIPE_STARTER_ANNUAL!,
        },
        {
          id: 'professional',
          name: process.env.PLAN_2_NAME || 'Professional',
          icon: process.env.PLAN_2_ICON || 'Zap',
          description: process.env.PLAN_2_DESCRIPTION || 'For growing teams & power users',
          monthlyPrice: Number.parseInt(process.env.PLAN_2_MONTHLY_PRICE || '149'),
          annualPrice: Number.parseInt(process.env.PLAN_2_ANNUAL_PRICE || '1490'),
          popular: (process.env.PLAN_2_POPULAR || 'true') === 'true',
          features: JSON.parse(process.env.PLAN_2_FEATURES || JSON.stringify([
            { text: '25,000 contacts', included: true },
            { text: '2,500 companies', included: true },
            { text: '5,000 deals', included: true },
            { text: '10 team members (+ $20/user)', included: true },
            { text: '25,000 emails/month', included: true },
            { text: 'Unlimited email templates', included: true },
            { text: 'Advanced email tracking & analytics', included: true },
            { text: 'All email server integrations', included: true },
            { text: 'Advanced automation (25 workflows)', included: true },
            { text: 'AI-powered enrichment & intelligence', included: true },
            { text: 'AI email composer (500 generations/mo)', included: true },
            { text: 'AI chatbot for customer queries', included: true },
            { text: 'Video campaigns (100 videos/mo)', included: true },
            { text: '50 video templates', included: true },
            { text: 'AI voice generation (25 voices)', included: true },
            { text: 'LinkedIn lead discovery', included: true },
            { text: 'Team collaboration & sharing', included: true },
            { text: 'Team member invitations', included: true },
            { text: 'Advanced analytics & reports', included: true },
            { text: 'Campaign A/B testing', included: true },
            { text: 'White-label branding', included: true },
            { text: 'Custom email server config', included: true },
            { text: 'Bulk operations & CSV management', included: true },
            { text: 'REST API access (1,000 calls/day)', included: true },
            { text: 'Priority email support', included: true },
          ])),
          buttonText: process.env.PLAN_2_BUTTON_TEXT || 'Start Free Trial',
          buttonVariant: (process.env.PLAN_2_BUTTON_VARIANT || 'primary') as 'primary' | 'outline',
          stripeMonthlyPriceId: process.env.STRIPE_PROFESSIONAL_MONTHLY!,
          stripeAnnualPriceId: process.env.STRIPE_PROFESSIONAL_ANNUAL!,
        },
        {
          id: 'enterprise',
          name: process.env.PLAN_3_NAME || 'Enterprise',
          icon: process.env.PLAN_3_ICON || 'Crown',
          description: process.env.PLAN_3_DESCRIPTION || 'For large teams with custom needs',
          monthlyPrice: Number.parseInt(process.env.PLAN_3_MONTHLY_PRICE || '499'),
          annualPrice: Number.parseInt(process.env.PLAN_3_ANNUAL_PRICE || '4990'),
          popular: (process.env.PLAN_3_POPULAR || 'false') === 'true',
          features: JSON.parse(process.env.PLAN_3_FEATURES || JSON.stringify([
            { text: 'Unlimited contacts', included: true },
            { text: 'Unlimited companies', included: true },
            { text: 'Unlimited deals', included: true },
            { text: 'Unlimited team members', included: true },
            { text: 'Unlimited emails/month', included: true },
            { text: 'Unlimited email templates', included: true },
            { text: 'Real-time email analytics & reports', included: true },
            { text: 'Custom email server integration', included: true },
            { text: 'Unlimited automation workflows', included: true },
            { text: 'Advanced AI enrichment & predictions', included: true },
            { text: 'Unlimited AI generations', included: true },
            { text: 'Dedicated AI chatbot instance', included: true },
            { text: 'Unlimited video campaigns', included: true },
            { text: 'Unlimited video templates', included: true },
            { text: 'Custom AI voice training', included: true },
            { text: 'Advanced lead discovery & scraping', included: true },
            { text: 'Advanced team permissions & roles', included: true },
            { text: 'Multi-team workspace management', included: true },
            { text: 'Custom analytics dashboards', included: true },
            { text: 'Multi-variant A/B testing', included: true },
            { text: 'Full white-label customization', included: true },
            { text: 'Custom domain & branding', included: true },
            { text: 'Advanced bulk operations', included: true },
            { text: 'Unlimited API access', included: true },
            { text: 'Dedicated account manager', included: true },
            { text: '24/7 priority phone & email support', included: true },
            { text: 'Custom integrations & development', included: true },
            { text: 'SLA guarantee (99.9% uptime)', included: true },
          ])),
          buttonText: process.env.PLAN_3_BUTTON_TEXT || 'Contact Sales',
          buttonVariant: (process.env.PLAN_3_BUTTON_VARIANT || 'outline') as 'primary' | 'outline',
          stripeMonthlyPriceId: process.env.STRIPE_ENTERPRISE_MONTHLY!,
          stripeAnnualPriceId: process.env.STRIPE_ENTERPRISE_ANNUAL!,
        },
      ],
      faqs: JSON.parse(process.env.PRICING_FAQS || JSON.stringify([
        {
          question: 'Can I change plans later?',
          answer: 'Yes! You can upgrade or downgrade your plan at any time. Changes take effect immediately and we\'ll prorate your billing accordingly.',
        },
        {
          question: 'What payment methods do you accept?',
          answer: 'We accept all major credit cards (Visa, Mastercard, Amex, Discover) and bank transfers for annual plans over $1,000.',
        },
        {
          question: 'Is there a free trial?',
          answer: 'Yes! All plans include a {trialDays}-day free trial with full feature access. No credit card required to start your trial.',
        },
        {
          question: 'What happens when I reach my limit?',
          answer: 'You\'ll receive notifications when approaching limits. You can purchase add-ons or upgrade your plan seamlessly without data loss.',
        },
      ])),
    };

    res.json(pricingData);
  } catch (error) {
    console.error('Error fetching pricing config:', error);
    res.status(500).json({ error: 'Failed to fetch pricing configuration' });
  }
});

// TODO: Add admin endpoints to update pricing configuration
// POST /api/pricing/config - Update pricing configuration (admin only)
// PUT /api/pricing/plans/:planId - Update specific plan (admin only)
// PUT /api/pricing/faqs - Update FAQs (admin only)

export default router;
