-- AlterTable: Add user preference columns to User table
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "language" TEXT NOT NULL DEFAULT 'en';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "dateFormat" TEXT NOT NULL DEFAULT 'MM/DD/YYYY';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "timeFormat" TEXT NOT NULL DEFAULT '12h';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "theme" TEXT NOT NULL DEFAULT 'light';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "compactView" BOOLEAN NOT NULL DEFAULT false;
